# Generated by Django 6.0.5 on 2026-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('identify', 'Identify Patient'), ('emergency_check', 'Emergency Check'), ('symptoms', 'Symptom Collection'), ('triage', 'Triage & Guidance'), ('booking', 'Appointment Booking'), ('manage_appointment', 'Manage Appointment'), ('done', 'Done')], default='identify', max_length=20),
        ),
    ]
